"""AGENTS.md generator - creates agent instructions from skills."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from ..core.manager import SkillManager, get_manager
from ..models.skill import Skill


def generate_agents_md(
    manager: SkillManager | None = None,
    include_global: bool = True,
    include_project: bool = True,
    categories: list[str] | None = None,
    output_path: Path | None = None,
) -> str:
    """Generate AGENTS.md content from installed skills.

    Args:
        manager: SkillManager instance (default: singleton)
        include_global: Include globally installed skills
        include_project: Include project-level skills
        categories: Filter to specific categories (None = all)
        output_path: If provided, write to this file

    Returns:
        Generated AGENTS.md content
    """
    if manager is None:
        manager = get_manager()

    # Get all installed skills
    skills = manager.list_installed()

    # Filter by source
    if not include_global:
        skills = [s for s in skills if s.source != "global"]
    if not include_project:
        skills = [s for s in skills if s.source != "project"]

    # Filter by category
    if categories:
        skills = [s for s in skills if s.manifest.category in categories]

    # Sort by category, then name
    skills.sort(key=lambda s: (s.manifest.category or "", s.manifest.name))

    # Generate content
    content = _generate_content(skills)

    # Write to file if path provided
    if output_path:
        output_path.write_text(content)

    return content


def _generate_content(skills: list[Skill]) -> str:
    """Generate the AGENTS.md content."""
    lines: list[str] = []

    # Header
    lines.append("# AGENTS.md")
    lines.append("")
    lines.append("This file provides instructions for AI agents working with this project.")
    lines.append(f"Generated by aiskills on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")

    if not skills:
        lines.append("No skills are currently installed.")
        lines.append("")
        lines.append("Install skills with: `aiskills install <source>`")
        return "\n".join(lines)

    # Table of contents
    lines.append("## Available Skills")
    lines.append("")

    # Group by category
    categories: dict[str, list[Skill]] = {}
    for skill in skills:
        cat = skill.manifest.category or "uncategorized"
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(skill)

    # Generate TOC
    for cat in sorted(categories.keys()):
        cat_display = cat.replace("/", " / ").title() if cat != "uncategorized" else "General"
        lines.append(f"### {cat_display}")
        lines.append("")

        for skill in categories[cat]:
            anchor = skill.manifest.name.lower().replace(" ", "-")
            tags = ", ".join(f"`{t}`" for t in skill.manifest.tags[:3])
            lines.append(f"- [{skill.manifest.name}](#{anchor}) - {skill.manifest.description[:60]}...")
            if tags:
                lines.append(f"  - Tags: {tags}")

        lines.append("")

    lines.append("---")
    lines.append("")

    # Skill details
    lines.append("## Skill Details")
    lines.append("")

    for skill in skills:
        lines.extend(_generate_skill_section(skill))
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("## Using Skills")
    lines.append("")
    lines.append("Skills can be accessed via:")
    lines.append("- **CLI**: `aiskills read <skill-name>`")
    lines.append("- **MCP**: Use `skill_read` tool with the skill name")
    lines.append("- **Search**: `aiskills search <query>` to find relevant skills")
    lines.append("")

    return "\n".join(lines)


def _generate_skill_section(skill: Skill) -> list[str]:
    """Generate a section for a single skill."""
    lines: list[str] = []

    # Skill header
    anchor = skill.manifest.name.lower().replace(" ", "-")
    lines.append(f"### {skill.manifest.name}")
    lines.append("")

    # Metadata
    lines.append(f"**Version:** {skill.manifest.version}")
    if skill.manifest.tags:
        tags = ", ".join(f"`{t}`" for t in skill.manifest.tags)
        lines.append(f"**Tags:** {tags}")
    if skill.manifest.category:
        lines.append(f"**Category:** {skill.manifest.category}")
    lines.append(f"**Source:** {skill.source}")
    lines.append("")

    # Description
    lines.append(f"> {skill.manifest.description}")
    lines.append("")

    # Context (when to use)
    if skill.manifest.context:
        lines.append("**When to use:**")
        lines.append("")
        for line in skill.manifest.context.strip().split("\n"):
            lines.append(f"> {line}")
        lines.append("")

    # Variables (if any)
    if skill.manifest.variables:
        lines.append("**Variables:**")
        lines.append("")
        for var_name, var in skill.manifest.variables.items():
            var_type = var.type if hasattr(var, "type") else "string"
            default = var.default if hasattr(var, "default") else None
            default_str = f" (default: `{default}`)" if default is not None else ""
            lines.append(f"- `{var_name}`: {var_type}{default_str}")
        lines.append("")

    # Content preview (first 10 lines)
    content_lines = skill.content.strip().split("\n")[:10]
    if content_lines:
        lines.append("<details>")
        lines.append("<summary>Preview</summary>")
        lines.append("")
        lines.append("```markdown")
        lines.extend(content_lines)
        if len(skill.content.strip().split("\n")) > 10:
            lines.append("...")
        lines.append("```")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    return lines


def sync_agents_md(
    output_path: Path | None = None,
    force: bool = False,
) -> Path:
    """Sync AGENTS.md with current skills.

    Args:
        output_path: Path to write AGENTS.md (default: ./AGENTS.md)
        force: Overwrite even if file exists and is newer

    Returns:
        Path to the generated file
    """
    if output_path is None:
        output_path = Path.cwd() / "AGENTS.md"

    content = generate_agents_md()
    output_path.write_text(content)

    return output_path
